from __future__ import annotations

import inspect

from research_agent import platform_core
from research_agent.datalab import datasets, preparation, runs


def test_platform_core_data_lab_facade_signatures_remain_stable() -> None:
    expected = {
        "create_data_lab_run": [
            "db",
            "user",
            "workspace",
            "workflow_type",
            "family",
            "method",
            "title",
            "source_asset_id",
            "request_payload",
        ],
        "finalize_data_lab_run_success": [
            "db",
            "user",
            "run_id",
            "title",
            "summary",
            "detail_path",
            "result_asset_id",
            "result_record_id",
            "output_payload",
        ],
        "finalize_data_lab_run_failure": ["db", "user", "run_id", "error", "title", "output_payload"],
        "list_data_lab_runs": ["db", "user", "workspace", "workflow_type", "limit"],
        "serialize_data_lab_run": ["db", "user", "run"],
        "load_dataset_frame": ["settings", "asset"],
        "normalize_dataset_frame": ["frame", "drop_duplicates"],
        "profile_dataset_asset": ["settings", "db", "user", "workspace", "asset_id"],
        "preview_dataset_preparation": [
            "settings",
            "db",
            "user",
            "workspace",
            "asset_id",
            "workflow_group",
            "template_id",
            "template_name",
            "variant_label",
            "variant_spec",
            "effective_specification",
            "options",
        ],
        "prepare_dataset_asset": [
            "settings",
            "db",
            "user",
            "workspace",
            "asset_id",
            "workflow_group",
            "include_columns",
            "required_columns",
            "numeric_columns",
            "binary_columns",
            "date_columns",
            "impute_columns",
            "impute_method",
            "winsorize_columns",
            "winsor_lower_quantile",
            "winsor_upper_quantile",
            "log_transform_columns",
            "standardize_columns",
            "minmax_scale_columns",
            "outlier_columns",
            "outlier_method",
            "outlier_threshold",
            "sort_column",
            "time_group_column",
            "difference_columns",
            "return_columns",
            "return_method",
            "lag_columns",
            "lag_periods",
            "lead_columns",
            "lead_periods",
            "rolling_mean_columns",
            "rolling_volatility_columns",
            "rolling_window",
            "drop_duplicates",
            "drop_missing_required",
            "template_id",
            "template_name",
            "variant_label",
            "variant_spec",
            "effective_specification",
        ],
        "preflight_model_analysis": [
            "settings",
            "db",
            "user",
            "workspace",
            "asset_id",
            "model_type",
            "dependent",
            "independents",
            "controls",
            "series_columns",
            "treatment_column",
            "post_column",
            "event_time_column",
            "lead_window",
            "lag_window",
            "omitted_period",
            "running_column",
            "rdd_cutoff",
            "cutoff",
            "rdd_bandwidth",
            "bandwidth",
            "entity_column",
            "time_column",
            "endogenous_column",
            "instrument_columns",
            "market_column",
            "risk_free_column",
            "smb_column",
            "hml_column",
            "spot_column",
            "strike_column",
            "maturity_column",
            "rate_column",
            "volatility_column",
            "arima_p",
            "arima_d",
            "arima_q",
            "garch_p",
            "garch_q",
            "forecast_steps",
            "var_lags",
            "option_steps",
            "kwargs",
        ],
    }

    for name, parameter_names in expected.items():
        assert list(inspect.signature(getattr(platform_core, name)).parameters) == parameter_names


def test_data_lab_extraction_modules_expose_backend_services() -> None:
    assert runs.create_run
    assert runs.finalize_run_success
    assert datasets.load_dataset_frame
    assert datasets.normalize_dataset_frame
    assert datasets.profile_dataset_asset
    assert preparation.prepare_dataset_frame
    assert preparation.prepare_dataset_asset
