export const endpoints = {
  assets: (workspaceId: string) => `/api/workspaces/${workspaceId}/assets`,
  authMe: "/api/auth/me",
  dataLabHistory: (workspaceId: string) => `/api/workspaces/${workspaceId}/data-lab/history`,
  dataLabLlmConfig: (workspaceId: string) => `/api/workspaces/${workspaceId}/data-lab/agent/llm-config`,
  dataLabLlmConfigTest: (workspaceId: string) => `/api/workspaces/${workspaceId}/data-lab/agent/llm-config/test`,
  dataLabNotebook: (workspaceId: string, runId: string) => `/api/workspaces/${workspaceId}/data-lab/agent/sessions/${runId}/notebook`,
  dataLabReport: (workspaceId: string, runId: string) => `/api/workspaces/${workspaceId}/data-lab/agent/sessions/${runId}/report`,
  dataLabSession: (workspaceId: string, runId: string) => `/api/workspaces/${workspaceId}/data-lab/agent/sessions/${runId}`,
  dataLabSessionMessages: (workspaceId: string, runId: string) => `/api/workspaces/${workspaceId}/data-lab/agent/sessions/${runId}/messages`,
  dataLabSessions: (workspaceId: string) => `/api/workspaces/${workspaceId}/data-lab/agent/sessions`,
  knowledge: (workspaceId: string) => `/api/workspaces/${workspaceId}/knowledge`,
  knowledgePublish: (workspaceId: string, recordId: string) => `/api/workspaces/${workspaceId}/knowledge/${recordId}/publish`,
  qualityRuns: (workspaceId: string) => `/api/workspaces/${workspaceId}/quality/runs`,
  qualityScorecard: (workspaceId: string) => `/api/workspaces/${workspaceId}/quality/scorecard`,
  researchRun: (workspaceId: string, runId: string) => `/api/workspaces/${workspaceId}/research/runs/${runId}`,
  researchRunPublish: (workspaceId: string, runId: string) => `/api/workspaces/${workspaceId}/research/runs/${runId}/publish`,
  researchRunRetry: (workspaceId: string, runId: string) => `/api/workspaces/${workspaceId}/research/runs/${runId}/retry`,
  researchRuns: (workspaceId: string) => `/api/workspaces/${workspaceId}/research/runs`,
  researchRuntime: (workspaceId: string) => `/api/workspaces/${workspaceId}/research/runtime`,
  teamLibrary: (teamId: string) => `/api/teams/${teamId}/library`,
  teamLibraryClone: (teamId: string, recordId: string) => `/api/teams/${teamId}/library/${recordId}/clone`,
  teams: "/api/teams",
  workbenchOverview: (workspaceId: string) => `/api/workspaces/${workspaceId}/workbench/overview`,
  workspaces: "/api/workspaces",
};
